spring:
  application:
    name: BookRecord
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: books
    password: postgress
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate