spring:
  application:
    name: BookRecord
  datasource:
    url: jdbc:sqlite:${user.home}/.books/books.db
    driver-class-name: org.sqlite.JDBC

open-library:
  base-url: https://openlibrary.org/api/books

